[build]
publish = "build"
command = "CI= yarn build"

[context.master]
command = "CI= yarn build:production"

[context.CROTest]
command = "CI= yarn build:production"

[context.deploy-preview]
command = "CI= yarn build:development"

[context.branch-deploy]
command = "CI= yarn build:development"
