[build]
publish = "build"
# command = "CI= yarn build"
command = "CI= npm run build"

[context.master]
command = "CI= yarn build:production"

[context.deploy-preview]
# command = "CI= yarn build:development"
command = "CI= npm run build:development"

[context.branch-deploy]
command = "CI= npm run build:development"
# command = "CI= yarn build:development"
